export const NoteOne = 'red'
export const NoteTwo = 'orange'
export const NoteThree = 'yellow'
export const NoteFour = 'green'
export const NoteFive = '#00FFFF'
export const NoteSix = '#000080'
export const NoteSeven = '#B266FF'
